export const COMPONENT_IDS = {
  LIST_STUFF_EDIT: 'list-stuff-edit',
  NAVBAR_ADD_STUFF: 'navbar-add-stuff',
  NAVBAR_LIST_STUFF: 'navbar-list-stuff',
  NAVBAR_LIST_STUFF_ADMIN: 'navbar-list-stuff-admin',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_COLLAPSE: 'navbar-collapse',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_MANAGE_DROPDOWN: 'navbar-manage-dropdown',
  NAVBAR_MANAGE_DROPDOWN_DATABASE: 'navbar-manage-dropdown-database',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_FIRST_NAME: 'sign-up-form-first-name',
  SIGN_UP_FORM_LAST_NAME: 'sign-up-form-last-name',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',
};
